### ISSUE TITLE
local setup not works

### ISSUE THREAD

**Issue by rdemirkoparan** [apigee-127/phrixus#1]
Hi,
Thanks for your awesome job.
I want to setup and look around but predefined steps (Getting Started Locally) produce lots of errors. I'm using usergrid-vagrant with default values.
Could you please explain how can I manage to install it locally?

**Comment by theganyo** [comment]
Sorry to be the bearer of bad news, but this hasn't been touched in 3 years... things have apparently broken in the mean time - and this was never made fully production-ready in the first place. If you want to pursue this project, I'm afraid you'll be digging in pretty much on your own.

**Comment by rdemirkoparan** [comment]
Yes, I saw that! Thanks..
